title: Verein Siedlung Leutschenbach
email: "siedlung@leutschenbach.ch"
description: >-
  Willkommen auf der Webseite des Vereins Siedlung Leutschenbach
baseurl: ""
url: "https://leutschenbach.ch"
minimal_mistakes_skin: "default"
logo: "/assets/images/logo.jpeg"

# Build settings
remote_theme: leutschenbach/minimal-mistakes

# Navigation im Header
header_pages:
  - index.md
  - gemeinschaftshaus.md
  - kontakt.md

plugins:
  - jekyll-include-cache
